# Generated by Django 4.0.2 on 2022-03-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produtos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Quantidade'),
        ),
    ]
