# Generated by Django 4.0.2 on 2022-03-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade'),
        ),
    ]
