# Generated by Django 4.0.2 on 2022-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padarias',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='padarias',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
